

version: "3"

services:
  rethinkdb1:
    platform: linux/amd64
    build: ./rethinkdb
    environment:
      - "DBCLUSTERHOSTS=rethinkdb2"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb1 --bind all"
    hostname: rethinkdb1
    networks:
      - rethink-net
    ports:
      - "8081:8080"
      - "28016:28015"
  rethinkdb2:
    platform: linux/amd64
    build: ./rethinkdb
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb2 --bind all"
    hostname: rethinkdb2
    networks:
      - rethink-net
    ports:
      - "8082:8080"
      - "28017:28015"
  
networks:
  rethink-net:
    driver: bridge
