

version: "3"

services:
  rethinkdb1:
    build: ./rethinkdb
    hostname: rethinkdb1
    networks:
      - rethink-net
    ports:
      - "8081:8080"
      - "28016:28015"
  
networks:
  rethink-net:
    driver: bridge
